### PR TITLE
Update VMs and SqueakSSL plugin

### PR DESCRIPTION
**Pull request by fniephaus**
Hi Dale,
@krono and @marceltaeumel fixed the SqueakSSL plugin:
http://forum.world.st/SqueakSSL-Binaries-td4820846.html

This PR replaces the binaries accordingly and removes unnecessary `libssl` dependencies.

Cheers,
Fabio

### CODE REVIEW

**Comment by dalehenrich** [comment]
@fniephaus [an error occurs during Pharo4.0 install](https://travis-ci.org/dalehenrich/builderCI/jobs/59415583#L334):

```
RUNNING TESTS...
ioLoadModule(/home/travis/build/dalehenrich/builderCI/images/pharo-vm/libSqueakSSL.so):
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
==== Startup Error: ZdcPluginMissing: SSL/TLS plugin initailization failed (VM plugin missing ? OS libraries missing ?)
```

Is it unrelated to your changes or not ... BTW travis-ci was non-oprational most of the day ...

**Comment by dalehenrich** [comment]
On second thought this may be unrelated but may point out that the os dependencies of Pharo4.0 have changed out from under us ...

**Comment by dalehenrich** [comment]
If Pharo4.0 is the only failure, could you update the .travis.yml with Pharo4.0 as an allowed failure? I'll have to fix Issue #94, sooner rather than later ...

**Comment by fniephaus** [comment]
@dalehenrich I've re-added `libssl1.0.0:i386` for Pharo and it's working just fine.
Also, I used the opportunity to update the vms.
There was still something wrong with the new SqueakSSL plugin, but I believe @krono has fixed it.

Once this PR is merged, we should publish a new builderCI release...

**Comment by fniephaus** [comment]
FYI: https://github.com/itsmeront/squeakssl/releases/tag/v0.2.0

**Comment by krono** [comment]
hold on … oh well…

**Comment by fniephaus** [comment]
For some weird reason the `GemStone-2.4.5.3` job [1] failed and I couldn't restart it. Apart from that, everything should work just fine. If it doesn't, I have to revert the changes...

[1] https://travis-ci.org/dalehenrich/builderCI/jobs/59702067

**Comment by fniephaus** [comment]
@krono btw: `libssl0.9.8:i386` is not available anymore anyways:
https://travis-ci.org/HPI-SWA-Teaching/SwaLint/jobs/59705529#L95

**Comment by krono** [comment]
please re-grab the SqueakSSL…

**Comment by fniephaus** [comment]
here you go: #96
btw: all builds passed

**Comment by krono** [comment]
Thanks again.

**Pull request merged**
