### PR TITLE
Fix screenshot mode

### LINKED ISSUE #75: Cannot use `SCREENSHOT=30` with Squeak-Trunk
Known issue? Any way [here's the error](https://travis-ci.org/dalehenrich/builderCI/jobs/40585526#L170)

### PR DESCRIPTION
**Pull request by fniephaus**
This should fix #75.

### CODE REVIEW

**Comment by fniephaus** [comment]
`#647.12` looks fine:
https://travis-ci.org/dalehenrich/builderCI/jobs/50277907

But I've no idea why `#647.11` failed (maybe a restart will do?):
https://travis-ci.org/dalehenrich/builderCI/jobs/50277906

**Comment by dalehenrich** [comment]
restarted the job, but segmentation faults are never a good thing:( ... Looks to me that the system is trying to draw a morph, but X isn't installed on travis ... Squeak does not seem to behave well in headless mode ...

**Comment by fniephaus** [comment]
We can easily enable xvfb when testing Squeak, so that it has a (virtual) X server.
But is this a good idea? What do you say?

**Comment by dalehenrich** [comment]
Ideally there would be proper error handling in Squeak when running in headless mode, but until that is taken care of, I suppose that a virtual x server is better than random segmentation faults:) 

Let's do that in a separate issue/pull request ... Could you submit an issue or pull request for this feature? Use an issue if you won't be getting to it real soon, so we don't forget. If your going to code it up right away a pull request is all that's needed.

**Pull request merged**
